
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khtlezzcdjahvqaflgvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtodGxlenpjZGphaHZxYWZsZ3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTQ2MjcsImV4cCI6MjA2MDM3MDYyN30.4UqMdojyZxfHf8aiEz82W9z0kdbv5YCcIY4TCamyPvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
